name: Bookstore API Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Setup JDK 17 (or your version)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # ✅ Build and run tests
      - name: Run Maven tests
        run: mvn clean test

      # ✅ Upload Allure results as artifacts
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      # ✅ Upload surefire reports for debugging
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
