name: Run API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: bookstore
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Python backend in background
        working-directory: bookstore
        run: |
          nohup uvicorn main:app --reload &

      - name: Wait for server to start
        run: sleep 10

      - name: Run Java API Tests
        working-directory: bookstore/automation-java/automation-java
        run: |
          mvn clean test
          mvn allure:report

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: bookstore/automation-java/automation-java/target/site/allure-maven-plugin

      - name: Install Allure Commandline
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Generate Allure Report
        run: |
          allure generate automation-java/automation-java/allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report




