name: Run API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: bookstore
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Python backend in background
        working-directory: bookstore
        run: |
          nohup uvicorn main:app --reload &

      - name: Wait for server to start
        run: sleep 10

      - name: Run Java API Tests
        working-directory: bookstore/automation-java/automation-java
        run: |
          mvn clean test
